language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
before_install:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
before_script:
  - git clone --branch=master --depth=1 --quiet git://github.com/WoltLab/WCF.git WCF
script:
  - find . -type f -name '*.php' -not -path "./WCF/*" |xargs -I file php -l file  > /dev/null
  - phpcs -p --extensions=php --standard="`pwd`/WCF/CodeSniff/WCF" --ignore="lib/system/api/" --ignore="WCF/" .